-- MySQL Script generated by MySQL Workbench
-- qua 20 mar 2019 18:17:24 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SGM` ;

-- -----------------------------------------------------
-- Schema SGM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGM` DEFAULT CHARACTER SET utf8 ;
USE `SGM` ;

-- -----------------------------------------------------
-- Table `SGM`.`sgm_servidores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_servidores` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_servidores` (
  `id_servidor` INT NOT NULL,
  PRIMARY KEY (`id_servidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_cursos` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_cursos` (
  `id_curso` INT NOT NULL,
  `fk_servidor` INT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_sgm_cursos_sgm_servidores1_idx` (`fk_servidor` ASC),
  CONSTRAINT `fk_sgm_cursos_sgm_servidores1`
    FOREIGN KEY (`fk_servidor`)
    REFERENCES `SGM`.`sgm_servidores` (`id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_estudantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_estudantes` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_estudantes` (
  `id_estudante` INT NOT NULL,
  `fk_curso` INT NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `periodo` INT(2) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estudante`, `fk_curso`),
  INDEX `fk_sgm_estudantes_sgm_cursos_idx` (`fk_curso` ASC),
  CONSTRAINT `fk_sgm_estudantes_sgm_cursos`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `SGM`.`sgm_cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_cadeiras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_cadeiras` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_cadeiras` (
  `id_cadeira` INT NOT NULL,
  `fk_curso` INT NOT NULL,
  `fk_servidor` INT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `periodo` INT NOT NULL,
  PRIMARY KEY (`id_cadeira`, `fk_curso`),
  INDEX `fk_sgm_cadeiras_sgm_cursos1_idx` (`fk_curso` ASC),
  INDEX `fk_sgm_cadeiras_sgm_servidores1_idx` (`fk_servidor` ASC),
  CONSTRAINT `fk_sgm_cadeiras_sgm_cursos1`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `SGM`.`sgm_cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgm_cadeiras_sgm_servidores1`
    FOREIGN KEY (`fk_servidor`)
    REFERENCES `SGM`.`sgm_servidores` (`id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_monitorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_monitorias` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_monitorias` (
  `id_monitorias` INT NOT NULL,
  `fk_estudante` INT NOT NULL,
  `fk_cadeira` INT NOT NULL,
  `fk_curso` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_monitorias`, `fk_estudante`, `fk_cadeira`, `fk_curso`),
  INDEX `fk_sgm_monitorias_sgm_estudantes1_idx` (`fk_estudante` ASC),
  INDEX `fk_sgm_monitorias_sgm_cadeiras1_idx` (`fk_cadeira` ASC),
  INDEX `fk_sgm_monitorias_sgm_cursos1_idx` (`fk_curso` ASC),
  CONSTRAINT `fk_sgm_monitorias_sgm_estudantes1`
    FOREIGN KEY (`fk_estudante`)
    REFERENCES `SGM`.`sgm_estudantes` (`id_estudante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgm_monitorias_sgm_cadeiras1`
    FOREIGN KEY (`fk_cadeira`)
    REFERENCES `SGM`.`sgm_cadeiras` (`id_cadeira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgm_monitorias_sgm_cursos1`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `SGM`.`sgm_cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_perguntas` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_perguntas` (
  `id_pergunta` INT NOT NULL,
  `fk_estudante` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pergunta`, `fk_estudante`),
  INDEX `fk_sgm_perguntas_sgm_estudantes1_idx` (`fk_estudante` ASC),
  CONSTRAINT `fk_sgm_perguntas_sgm_estudantes1`
    FOREIGN KEY (`fk_estudante`)
    REFERENCES `SGM`.`sgm_estudantes` (`id_estudante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_respostas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_respostas` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_respostas` (
  `id_respostas` INT NOT NULL,
  `fk_pergunta` INT NOT NULL,
  `fk_estudante` INT NOT NULL,
  `texto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_respostas`, `fk_pergunta`, `fk_estudante`),
  INDEX `fk_sgm_respostas_sgm_perguntas1_idx` (`fk_pergunta` ASC),
  INDEX `fk_sgm_respostas_sgm_estudantes1_idx` (`fk_estudante` ASC),
  CONSTRAINT `fk_sgm_respostas_sgm_perguntas1`
    FOREIGN KEY (`fk_pergunta`)
    REFERENCES `SGM`.`sgm_perguntas` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgm_respostas_sgm_estudantes1`
    FOREIGN KEY (`fk_estudante`)
    REFERENCES `SGM`.`sgm_estudantes` (`id_estudante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_votos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_votos` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_votos` (
  `id_votos` INT NOT NULL,
  `fk_respostas` INT NOT NULL,
  `fk_estudante` INT NOT NULL,
  `fk_pergunta` INT NOT NULL,
  PRIMARY KEY (`id_votos`, `fk_estudante`),
  INDEX `fk_sgm_votos_sgm_respostas1_idx` (`fk_respostas` ASC),
  INDEX `fk_sgm_votos_sgm_estudantes1_idx` (`fk_estudante` ASC),
  INDEX `fk_sgm_votos_sgm_perguntas1_idx` (`fk_pergunta` ASC),
  CONSTRAINT `fk_sgm_votos_sgm_respostas1`
    FOREIGN KEY (`fk_respostas`)
    REFERENCES `SGM`.`sgm_respostas` (`id_respostas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgm_votos_sgm_estudantes1`
    FOREIGN KEY (`fk_estudante`)
    REFERENCES `SGM`.`sgm_estudantes` (`id_estudante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgm_votos_sgm_perguntas1`
    FOREIGN KEY (`fk_pergunta`)
    REFERENCES `SGM`.`sgm_perguntas` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_cadeiras_cursando`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_cadeiras_cursando` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_cadeiras_cursando` (
  `id_cadeira_cursando` INT NOT NULL AUTO_INCREMENT,
  `fk_estudante` INT NOT NULL,
  `fk_curso` INT NOT NULL,
  `fk_cadeira` INT NOT NULL,
  PRIMARY KEY (`id_cadeira_cursando`, `fk_estudante`, `fk_curso`, `fk_cadeira`),
  INDEX `fk_sgm_cadeiras_cursando_sgm_estudantes1_idx` (`fk_estudante` ASC, `fk_curso` ASC),
  INDEX `fk_sgm_cadeiras_cursando_sgm_cadeiras1_idx` (`fk_cadeira` ASC),
  CONSTRAINT `fk_sgm_cadeiras_cursando_sgm_estudantes1`
    FOREIGN KEY (`fk_estudante` , `fk_curso`)
    REFERENCES `SGM`.`sgm_estudantes` (`id_estudante` , `fk_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgm_cadeiras_cursando_sgm_cadeiras1`
    FOREIGN KEY (`fk_cadeira`)
    REFERENCES `SGM`.`sgm_cadeiras` (`id_cadeira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGM`.`sgm_monitores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SGM`.`sgm_monitores` ;

CREATE TABLE IF NOT EXISTS `SGM`.`sgm_monitores` (
  `id_monitor` INT NOT NULL,
  `fk_estudante` INT NOT NULL,
  `fk_curso` INT NOT NULL,
  `fk_servidor` INT NOT NULL,
  `fk_cadeira` INT NOT NULL,
  PRIMARY KEY (`id_monitor`, `fk_estudante`, `fk_curso`, `fk_servidor`, `fk_cadeira`),
  INDEX `fk_monitores_sgm_estudantes1_idx` (`fk_estudante` ASC),
  INDEX `fk_monitores_sgm_cursos1_idx` (`fk_curso` ASC),
  INDEX `fk_monitores_sgm_servidores1_idx` (`fk_servidor` ASC),
  INDEX `fk_monitores_sgm_cadeiras1_idx` (`fk_cadeira` ASC),
  CONSTRAINT `fk_monitores_sgm_estudantes1`
    FOREIGN KEY (`fk_estudante`)
    REFERENCES `SGM`.`sgm_estudantes` (`id_estudante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitores_sgm_cursos1`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `SGM`.`sgm_cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitores_sgm_servidores1`
    FOREIGN KEY (`fk_servidor`)
    REFERENCES `SGM`.`sgm_servidores` (`id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitores_sgm_cadeiras1`
    FOREIGN KEY (`fk_cadeira`)
    REFERENCES `SGM`.`sgm_cadeiras` (`id_cadeira`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
